[package]
name = "day19"
version = "0.1.0"
authors = ["coriolinus <coriolinus@gmail.com>"]

[lib]
name = "day18lib"
path = "src/lib.rs"

[[bin]]
name = "day18bin"
path = "src/bin.rs"

[dependencies]
util = { path = "../util"}
