[package]
name = "day18"
version = "0.1.0"
authors = ["coriolinus <coriolinus@gmail.com>"]
edition = "2018"

[dependencies]
aoc2015 = { path = ".." }
color-eyre = "0.5.10"
parse-display = "0.4.0"
structopt = "0.3.21"
thiserror = "1.0.22"
