[package]
name = "day13"
version = "0.1.0"
authors = ["coriolinus <coriolinus@gmail.com>"]

[lib]
name = "day13lib"
path = "src/lib.rs"

[[bin]]
name = "day13bin"
path = "src/bin.rs"

[dependencies]
util = { path = "../util"}
permutohedron = "^0.1.7"
