[package]
name = "day05"
version = "0.1.0"
authors = ["coriolinus <coriolinus@gmail.com>"]
edition = "2018"

[dependencies]
aoc2015 = { path = ".." }
color-eyre = "0.5.10"
lazy_static = "1.4.0"
maplit = "1.0.2"
structopt = "0.3.21"
thiserror = "1.0.22"

[dev-dependencies]
rstest = "0.6.4"
